# Prettier friendly markdownlint config (all formatting rules disabled).
extends: markdownlint/style/prettier

# Disables specific rules.
MD024: false # Allows multiple headers with the same content.
MD033: false # Allows inline HTML.
MD041: false # Allows the first line to not be a top-level heading.
