brace_style = "PreferSameLine"
comment_width = 128
edition = "2021"
fn_single_line = true
format_strings = true
max_width = 128
merge_derives = true
reorder_imports = true
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
use_small_heuristics = "Max"
wrap_comments = true
