# Suggestions can sometimes take longer on CI machines, leading to inconsistent results.
suggestionsTimeout: 5000 # ms
version: "0.2"
language: "en"
ignorePaths:
  - img/
words:
  [
    alibabacloud,
    amonrayfa,
    androideabi,
    apikey,
    armv,
    bluehost,
    chrono,
    clippy,
    consec,
    crazydomains,
    ddns,
    dnspod,
    dotenvy,
    dreamhost,
    dunder,
    dynadot,
    dynu,
    emscripten,
    enom,
    epik,
    gandi,
    getline,
    gnueabi,
    gnueabihf,
    godaddy,
    ident,
    idents,
    ionos,
    koseka,
    mabe,
    markdownlint,
    merror,
    metalinter,
    metalinters,
    msvc,
    mwapi,
    namecheap,
    namesilo,
    njsproj,
    nocapture,
    ntvs,
    opensrs,
    porkbun,
    println,
    pycache,
    rayfa,
    reqwest,
    resellerclub,
    rkyv,
    rollup,
    rustdoc,
    rustdocflags,
    rustup,
    secretapikey,
    serde,
    squarespace,
    taiki,
    trunkio,
    wapi,
    venv,
  ]
