# Suggestions can sometimes take longer on CI machines, leading to inconsistent results.
suggestionsTimeout: 5000 # ms
version: "0.2"
words:
  [
    alibabacloud,
    amonrayfa,
    androideabi,
    armv,
    bluehost,
    chrono,
    clippy,
    crazydomains,
    ddns,
    dnspod,
    dotenvy,
    dreamhost,
    dynadot,
    dynu,
    emscripten,
    enom,
    epik,
    gandi,
    getline,
    gnueabi,
    gnueabihf,
    godaddy,
    ionos,
    koseka,
    mabe,
    markdownlint,
    msvc,
    namecheap,
    namesilo,
    njsproj,
    nocapture,
    ntvs,
    opensrs,
    porkbun,
    println,
    rayfa,
    reqwest,
    resellerclub,
    rollup,
    rustup,
    serde,
    squarespace,
    trunkio,
    wapi,
  ]
