# Suggestions can sometimes take longer on CI machines, leading to inconsistent results.
suggestionsTimeout: 5000 # ms
version: "0.2"
words:
  [
    amonrayfa,
    alibabacloud,
    bluehost,
    chrono,
    clippy,
    ddns,
    dnspod,
    dotenvy,
    dreamhost,
    dynadot,
    enom,
    epik,
    gandi,
    godaddy,
    getline,
    ionos,
    koseka,
    mabe,
    markdownlint,
    namecheap,
    namesilo,
    njsproj,
    ntvs,
    opensrs,
    porkbun,
    rayfa,
    reqwest,
    resellerclub,
    rollup,
    serde,
    squarespace,
    trunkio,
    wapi,
  ]
